version: '3.3'
services:
  gitbucket:
    container_name: gitbucket
    image: gitbucket:4.32.0
    build: ./gitbucket
    ports:
      - 9080:8080
      - 29418:29418
    volumes:
      - ./gitbucket/volume:/gitbucket